Add insect sex pheromones to GlobalChem
Global-Chem/global-chem pull request #321
Opened 2024-09-05 22:22 UTC by Lyq322

Issue #320

2024-09-13 11:55 UTC, ANUGAMAGE requested changes
Hi @Lyq322,
Couple of things to consider before merging.

1)
'cis-11-octadecenal': 'CCCCCC\C=C/CCCCCCCCCC=O'
In this case as an example, if the string contains \C or C/(any other combination) , Python would look for an escape sequence, which could lead to a syntax error or unintended behavior.

With Raw String (Correct Handling):
'cis-11-octadecenal': r 'CCCCCC\C=C/CCCCCCCCCC=O'
Here, the r prefix ensures that all characters in the string are taken literally, preserving the intended SMILES notation, including the backslashes. This is crucial for accurately representing the molecular structure and ensuring that cheminformatics software can correctly parse the SMILES string.

2)
Need to add smarts def in to the code
```
    @staticmethod
    def get_smarts():

         smarts = {
         }

         return smarts
```

2024-09-25 15:36 UTC, Sulstice commented
@Lyq322Anu is correct there because of the `/` character it breaks in some operating systems outputs so we prefix the string with r we believe is the fix.

2024-09-25 15:44 UTC, Sulstice commented
@Lyq322 Could you now update the `global_chem.py` file with your node in the added list and also the `README.md` with yours and my name for insects. We need to add the reference too. 

@ANUGAMAGE Can you get ready for a new version release and testing.

2024-09-26 15:48 UTC, Sulstice approved these changes

2024-09-29 07:40 UTC, ANUGAMAGE approved these changes

2024-09-30 04:44 UTC, merged